using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class bookDisplayUI : MonoBehaviour
{
    public GameObject obj;
    public Text bookText;
    player playerScript;


    void Start(){
        playerScript = (player)obj.gameObject.GetComponent(typeof(player));
    }
    // Update is called once per frame
    void Update()
    {
        
        if(playerScript.key){
            bookText.text = "BOOKS: " + playerScript.numOfBooks + "     KEY";
        }
        else{
            bookText.text = "BOOKS: " + playerScript.numOfBooks;
        }
    }
}
